name: server_dart
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  share_flutter:
    path: ../share_flutter
  path: ^1.8.0
  html: ^0.15.1
  http_parser: ^4.0.2
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  shelf_multipart: ^1.0.0
  shelf_static: ^1.1.1
  mongo_dart: ^0.9.1
  mime: ^1.0.2
  dart_jsonwebtoken: ^2.6.1
  encrypt: ^5.0.1
  bcrypt: ^1.1.3
  timezone: ^0.9.0
  mailer: ^6.0.0
  synchronized: ^3.0.1
  pdf: ^3.10.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
